version: "3"

services:
  url-random:
    container_name: url-random
    restart: unless-stopped
    build: .
    ports:
      - "80:8080"
    environment:
      TZ: Asia/Shanghai
    volumes:
      - $PWD/data:/app
