---
name: "pre-release"

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - 'src/**'
      - 'build.gradle.kts'
      - 'gradle.properties'
      - 'settings.gradle.kts'
      - 'frontend/**'
permissions:
  contents: write
jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            **/*.zip
            
  publish-dockerhub:
    runs-on: ubuntu-latest
    steps:
    - name: Build Image
      run: docker build -t yunkuangao/url-random:pre-latest .
    - name: Login to Registry
      run: docker login --username=${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Push Image
      run: docker push yunkuangao/url-random:pre-latest
