name: Publish

on:
  push:
    tags:
      - "v*"
      
permissions:
  contents: write
  
jobs:
  tagged-release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
          
      - name: make gradlew executable
        run: chmod +x ./gradlew

      - name: build gradle
        run: ./gradlew build

      - name: ls frontend
        run: ls ./frontend/public
      - name: ls frontend build
        run: ls ./frontend/public/build
      - name: ls build resources
        run: ls ./build/resources/main
      - name: ls build resources static
        run: ls ./build/resources/main/static

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            **/url-random-shadow.zip
            **/url-random-all.jar

  publish-docker:
    needs: tagged-release
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.0
        with:
          images: yunkuangao/url-random
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=url-random
            org.opencontainers.image.description=随机链接获取器
            org.opencontainers.image.author=yunkuangao
            org.opencontainers.image.url=https://github.com/yunkuangao/url-random/
            org.opencontainers.image.source=https://github.com/yunkuangao/url-random/
            org.opencontainers.image.version={{ version }}
            org.opencontainers.image.revision={{ GITHUB_SHA }}
            org.opencontainers.image.licenses=MIT

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            github_version=$GITHUB_REF_NAME
