name: Publish Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    tags:
      - "v*"
  pull_request:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.1.0
        with:
          images: yunkuangao/url-random
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=url-random
            org.opencontainers.image.description=用于将多个url随机获取
            org.opencontainers.image.author=yunkuangao
            org.opencontainers.image.url=https://github.com/yunkuangao/url-random/
            org.opencontainers.image.source=https://github.com/yunkuangao/url-random/
            org.opencontainers.image.version=${{ version }}
            org.opencontainers.image.revision=${{ GITHUB_SHA }}
            org.opencontainers.image.licenses=MIT
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3.2.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
